# Hydra-based CIR sensing configuration values
radios:
  - channel: 9
  - cir_sample: 24
  - cir_starting_idx: 0
  - fps: 100
  - duration: 30  # seconds
  - nodes: "0123"
  - distance_between_nodes: [522, 440, 689, 700, 483] # 01,02,03,12,13 in cm

rooms:
  - room: "boelter"
  - desk_num: 2
  - desk_layout: "1x2" # "1x1", "1x2", "2x2", "1x1T": transposed
  - humans: 1
  - activity: "1" # "0": empty, "1": sitting, "2": standing
  - tag: [374,295,440,367] # to 0,1,2,3

